    %Filter lijst voor eyelink messages
    %Elk statement wordt maar een keer per trial geavuleerd. Let wel, MARKER is een speciaal case, waarvan elke instantie in een lijstje wordt toegevoegd
eyelinkMessages = {'TRIAL_RESULT','TRIALID','REACTION_TIME','MARKER','SYNCTIME','CHANGE_COMMING','Completed','SWITCH', 'FINAL_DESTINATION', 'PROBE_ORIENTATION', 'PROBE_TIMING','RESPONSE', 'ORIENTATION','TARGET_ON','SBLINK','EBLINK'};

    %Een hoop constanten.

HORIZONTAL_AXIS = 1;
VERTICAL_AXIS = 2;
CHANGE_STATIC =0;
CHANGE_DYNAMIC = 1;

TARGET = 1;
ALTERN = 2;
DISTRACTOR = 3;
ALTERN2 = 4;
MASK = 5;
EMPTY = 6;
FIRST_ELEMENT = 7;
SECOND_ELEMENT = 8;
JUMPED_ELEMENT = 9;
MOST_SALIENT_ELEMENT = 10;
MIDDLE_SALIENT_ELEMENT = 11;
LEAST_SALIENT_ELEMENT = 12;
NON_TARGET = 13;
JUMP = 14;
NONE = 15;
BLANK = 16;  

ELEMENT_HS = 4;
ELEMENT_MS = 5;
ELEMENT_LS = 6;
    
CONDITION_DOUBLE_TARGET = 101; 
CONDITION_SINGLE_TARGET = 102;

CONDITION_TARGET_PROBE = 103;
CONDITION_DISTRACTOR_PROBE = 104;
CONDITION_CENTER_PROBE = 105;

CONDITION_SINGLE_TARGET_HC      = 921;
CONDITION_DISTRACTOR_PROBE_HC   = 922;
CONDITION_SINGLE_TARGET_LC      = 923;
CONDITION_DISTRACTOR_PROBE_LC   = 924;

CONDITION_CAUSAL = 1;
CONDITION_NON_CAUSAL = 2;
CONDITION_CAUSAL_DELAY = 3;
CONDITION_NON_CAUSAL_DELAY = 4;

CONDITION_HIGH_NOISE = 1;
CONDITION_LOW_NOISE = 2;
CONDITION_NO_NOISE = 3;

CONDITION_STATIC = 101;
CONDITION_DYNAMIC = 102;
CONDITION_CONTROLE = 3;
CONDITION_STATICC = 4;
CONDITION_DYNAMICC = 5;

CONDITION_CONTRAST_HIGH = 13;
CONDITION_CONTRAST_LOW = 14;

CONDITION_SAME = 18;
CONDITION_DIFFERENT = 19;

CONDITION_SOUTHEAST = 12;
CONDITION_SOUTHWEST = 13;
CONDITION_NORTHEAST = 14;
CONDITION_NORTHWEST = 15;

CONDITION_LARGE_LARGE = 91;
CONDITION_SMALL_SMALL = 92;
CONDITION_SMALL_LARGE = 93;
CONDITION_LARGE_SMALL = 94;

CONDITION_IOR = 21;
CONDITION_NO_IOR = 22;
CONDITION_SINGLE_IOR = 23;
CONDITION_DOUBLE_IOR = 24;
CONDITION_TO_IOR = 25;
CONDITION_FROM_IOR = 26;
CONDITION_TARGET_IOR = 27;
CONDITION_DISTRACTOR_IOR = 28;

CONDITION_DOUBLE_IOR_STEP = 29;
CONDITION_NO_IOR_STEP = 30;
CONDITION_TO_IOR_STEP = 31;
CONDITION_FROM_IOR_STEP = 32;


CONDITION_NO_FAC = 32;
CONDITION_SINGLE_FAC = 33;
CONDITION_DOUBLE_FAC = 34;
CONDITION_TO_FAC = 35;
CONDITION_FROM_FAC = 36;
CONDITION_TARGET_FAC = 37;
CONDITION_DISTRACTOR_FAC = 38;

CONDITION_REGULAR_TRIAL = 1;
CONDITION_STEP_TRIAL = 2;
CONDITION_OFFSET_TRIAL = 3;

CONDITION_EARLY = 39;
CONDITION_LATE = 49;

CONDITION_GRID = 24;
CONDITION_NOGRID = 23;

CONDITION_SIMILAR = 7;
CONDITION_MEDIUM = 8;
CONDITION_REMOTE = 9;

CONDITION_INCLUSION = 10;
CONDITION_EXCLUSION = 11;

CONDITION_HIGH_SALIENT = 201;
CONDITION_LOW_SALIENT = 202;
CONDITION_HIGH_NON_SALIENT = 203;
CONDITION_LOW_NON_SALIENT = 204;
CONDITION_HIGH_SALIENT_LARGE = 205;

CONDITION_MOST_SALIENT = 12;
CONDITION_LEAST_SALIENT = 13;
CONDITION_MIDDLE_SALIENT = 14;
CONDITION_NON_SALIENT = 15;
CONDITION_FOVEAL = 16;

CONDITION_MOST_LEAST_SALIENT = 31;
CONDITION_MIDDLE_LEAST_SALIENT = 32;
CONDITION_MOST_MIDDLE_SALIENT = 33;

CONDITION_GO = 61;
CONDITION_NO_GO = 62;
CONDITION_GO_BACK = 63;
CONDITION_REMAPPED = 64;
CONDITION_CONTROL = 65;

CONDITION_NO_BLUR       = 801;
CONDITION_LIGHT_BLUR    = 802;
CONDITION_HEAVY_BLUR    = 803;

CONDITION_NOVEL         = 901;
CONDITION_TWO_BACK      = 902;
CONDITION_FOUR_BACK     = 903;
CONDITION_NO_PROBE      = 904;

CONDITION_FIXON_PLACEOFF        = 911;
CONDITION_FIXOFF_PLACEOFF       = 912;
CONDITION_FIXOFF_PLACEON        = 913;
CONDITION_FIXON_PLACEON         = 914;
CONDITION_FIXGAP_PLACEON        = 915;
CONDITION_FIXGAP_PLACEOFF       = 916;

CONDITION_NO_TDOA_TARGET        = 931;
CONDITION_SHORT_TDOA_TARGET     = 932;
CONDITION_LONG_TDOA_TARGET      = 933;
CONDITION_NO_TDOA_DISTRACTOR    = 934;
CONDITION_SHORT_TDOA_DISTRACTOR = 935;
CONDITION_LONG_TDOA_DISTRACTOR  = 936;

CONDITION_GAP       = 941;
CONDITION_OVERLAP   = 942;


CONDITION_FIRST_SPA = 1;
CONDITION_FIRST_MIR = 2;
CONDITION_SECOND_SPA = 3;
CONDITION_SECOND_MIR = 4;

CONDITION_ONE_CLOSE = 1;
CONDITION_TWO_CLOSE = 2;
CONDITION_ONE_FAR = 3;
CONDITION_TWO_FAR = 4;

CONDITION_REDGREEN_TG = 1;
CONDITION_REDGREEN_DG = 2;
CONDITION_GREEN_TG = 3;
CONDITION_GREEN_DG = 4;

CONDITION_MOST_LEAST_SALIENT = 32;
CONDITION_MIDDLE_LEAST_SALIENT = 42;
CONDITION_MOST_MIDDLE_SALIENT = 52;

CONDITION_NO_JITTER = 30;
CONDITION_JITTER = 31;

CONDITION_BLACK = 1;
CONDITION_GREY = 2;
CONDITION_WHITE = 3;

CONDITION_TARGET_PRESENT = 1;
CONDITION_TARGET_ABSENT = 2;

CONDITION_LEFT_TILT = 54;
CONDITION_RIGHT_TILT = 55;

CONDITION_JUMP_FORWARD = 56;
CONDITION_JUMP_BACKWARD = 57;

CONDITION_SALIENCY_CONGRUENT = 71;
CONDITION_SINGLETON_CONGRUENT = 72;
CONDITION_SALIENCY_INCONGRUENT = 73;
CONDITION_SINGLETON_INCONGRUENT = 74;

CONDITION_DISTANCE_NEAREST = 76;
CONDITION_DISTANCE_NEAR = 77;
CONDITION_DISTANCE_MEDIUM = 78;
CONDITION_DISTANCE_FAR = 79;
CONDITION_DISTANCE_FARTHEST = 80;

CONDITION_CENTER_RING = 61;
CONDITION_MIDDLE_RING = 62;
CONDITION_OUTER_RING = 63;

CONDITION_NO_ADAPTATION = 110;
CONDITION_ADAPTATION = 111;

CONDITION_TARGET_DET = 120;
CONDITION_DISTRACTOR_DET = 121;

CONDITION_LARGE_LARGE = 91;
CONDITION_SMALL_SMALL = 92;
CONDITION_SMALL_LARGE = 93;
CONDITION_LARGE_SMALL = 94;

CONDITION_SIZE_LARGE = 99;
CONDITION_SIZE_MEDIUM = 98;
CONDITION_SIZE_SMALL = 97;

CONDITION_HIGH_LOW = 91;
CONDITION_LOW_HIGH = 92;

CONDITION_SHAPE_HOR_ELLIPSE = 101;
CONDITION_SHAPE_VERT_ELLIPSE = 102;

CONDITION_SHAPE_LEFT_POINT_TRIANGLE = 103;
CONDITION_SHAPE_RIGHT_POINT_TRIANGLE = 104;

CONDITION_MOTION_CONGRUENT = 171;
CONDITION_MOTION_INCONGRUENT = 172;

CONDITION_ABOVE = 181;
CONDITION_BELOW = 182;

TILTED_LEFT = 1;
TILTED_RIGHT = 2;

LOWLOW = 1;
HIGHLOW = 2;
LOWHIGH = 3;
HIGHHIGH = 4;

NO_CHANGE = 0;
DYNAMIC_CHANGE = 1;
STATIC_CHANGE = 2;

EXP_SECOND_SACCADE = 1;
EXP_CONTRAST_SENSITIVITY = 2;
EXP_SWITCHING_PERIPHERY = 3;

EXP_DETECTION = 4;
EXP_DISCRIMINATION = 5;
EXP_IDENTIFICATION = 6;

EYL_RECORDING_INCOMPLETE = 0;
EYL_RECORDING_COMPLETE = 1;
EYL_RECORDING_INTERRUPT = 2;
EYL_RECORDING_NOTSTARTED = 3;
EYL_EVENT_ISSUE             = 4;

DENSE = 1;
SPARSE = 2;
SPARSEST = 3;
DENSEST = 4;
       
LEFT_TOP = 1;
RIGHT_TOP = 2;
LEFT_BOTTOM = 3;
RIGHT_BOTTOM = 4;

FINAL_POS = 1;
SECOND_CUE = 2;
FIRST_CUE = 3;
START_POS = 4;
SECOND_POS = 5;
FIRST_POS = 6;

CUE_CLOSE_POTENTIAL = 1;
CUE_FAR_POTENTIAL = 2;
CUE_CLOSE_DISTRACTOR = 3;
CUE_FAR_DISTRACTOR = 4;

DELAY = 1;
NO_DELAY = 2;

PP_ROUTE = 1;
PD_ROUTE = 2;
DP_ROUTE = 3;
DD_ROUTE = 4;
NEW_ROUTE = 5;
